---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mongo_standalone_no_encryption
    groups:
      - no_encrypt
  - name: mongo_standalone_encryption
    groups:
      - encrypt
  - name: mongo_cluster_1
    groups:
      - cluster
  - name: mongo_cluster_2
    groups:
      - cluster
  - name: mongo_cluster_3
    groups:
      - cluster
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - destroy
